service: node-lambda-assignment

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1 
  memorySize: 128
  tracing:
    apiGateway: true
    lambda: true
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true

layers:
  commonLibs:
    path: layers
    compatibleRuntimes:
      - nodejs12.x

package: 
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - package-lock.json

functions:
  blog-app:
    handler: app/app.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true